FROM nginx:mainline

RUN apt-get update
RUN apt-get install vim -y
RUN echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install python-certbot-nginx -t stretch-backports -y

COPY sites-enabled/rocket.conf.template /etc/nginx/conf.d/rocket.conf.template

CMD /bin/bash -c "envsubst '\$FLOWER_DELTA_SERVICE_HOST \$FLOWER_DELTA_SERVICE_PORT' < /etc/nginx/conf.d/rocket.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"



certbot certonly --manual --preferred-challenges=dns --manual-auth-hook /path/to/dns/authenticator.sh --manual-cleanup-hook /path/to/dns/cleanup.sh -d secure.example.com